name: ci
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "below script execution"
      - name: execute permission
        run: chmod +x a.sh
      - name: running script
        run: ./a.sh > output.txt
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/output.txt

